apiVersion: v1
kind: Service
metadata:
  name: easy-mail
spec:
  type: NodePort
  selector:
    app: easy-mail
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 3678